#pragma once 
#define BLUESTREET_DEVICE 0x8000 
#define IOCTL_BLUESTREET_SEND_DATA CTL_CODE(BLUESTREET_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_BLUESTREET_RECEIVE_DATA CTL_CODE(BLUESTREET_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_BLUESTREET_DEBUG_PRINT CTL_CODE(BLUESTREET_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
//struct sMSG {
//    WCHAR Path[256];
//    WCHAR DLLs[256];
//    // Добавьте любое количество строк, которые вам нужны
//};



